export type PageVariant = "list" | "statistics" | "workflow" | "logs";

export type FeaturePresentation = {
  variant: PageVariant;
  filters: string[];
  columns: string[];
  primaryAction?: string;
  rowAction?: string;
  metrics?: string[];
};

const statisticsColumns = ["统计维度", "应到人数", "已到人数", "未到人数", "报到率"];

export const featurePresentations: Record<string, FeaturePresentation> = {
  classes: { variant: "list", filters: ["院系名称", "专业名称", "班级名称", "所属年级"], columns: ["院系名称", "专业名称", "班级名称", "班级代码", "所属年级", "班主任工号", "班级群号"], primaryAction: "新增班级", rowAction: "编辑" },
  payments: { variant: "list", filters: ["姓名", "学号", "院系", "缴费状态"], columns: ["姓名", "学号", "缴费项目", "应缴金额", "实缴金额", "缴费时间", "缴费状态"], primaryAction: "导入缴费信息", rowAction: "查看" },
  "payment-proof": { variant: "list", filters: ["姓名", "学号", "凭证状态"], columns: ["姓名", "学号", "缴费项目", "凭证附件", "提交时间", "凭证状态"], rowAction: "审核" },
  leave: { variant: "workflow", filters: ["姓名", "学号", "请假类型", "审核状态", "请假时间"], columns: ["申请编号", "姓名", "学号", "请假类型", "开始时间", "结束时间", "请假天数", "当前节点", "审核状态"], primaryAction: "发起请假", rowAction: "流程详情" },
  "leave-type": { variant: "list", filters: ["类型名称", "启用状态"], columns: ["类型名称", "类型编码", "最长天数", "是否需要附件", "审批层级", "启用状态"], primaryAction: "新增请假类型", rowAction: "编辑" },
  "leave-cancel": { variant: "workflow", filters: ["申请人", "审核状态"], columns: ["申请编号", "申请人", "业务类型", "申请时间", "申请陈述", "当前节点", "审核状态"], primaryAction: "发起销假", rowAction: "审核" },
  "student-card": { variant: "workflow", filters: ["姓名", "学号", "申办类型", "审核状态"], columns: ["申请编号", "姓名", "学号", "申办类型", "申请原因", "提交时间", "审核状态", "制卡状态"], primaryAction: "学生证补办", rowAction: "办理" },
  "return-school": { variant: "list", filters: ["节假日", "姓名", "学号", "返校状态"], columns: ["姓名", "学号", "院系", "假期去向", "计划返校时间", "实际返校时间", "返校状态"], rowAction: "确认返校" },
  holiday: { variant: "list", filters: ["假期名称", "学年", "启用状态"], columns: ["假期名称", "开始日期", "结束日期", "去向填报时间", "返校确认时间", "启用状态"], primaryAction: "新增节假日", rowAction: "配置" },
  complaints: { variant: "workflow", filters: ["申请人", "审核状态"], columns: ["申请编号", "申请人", "业务类型", "申请时间", "申请陈述", "当前节点", "审核状态"], primaryAction: "登记投诉", rowAction: "处理" },
  "work-study": { variant: "workflow", filters: ["申请人", "审核状态"], columns: ["申请编号", "申请人", "业务类型", "申请时间", "申请陈述", "当前节点", "审核状态"], primaryAction: "岗位申请", rowAction: "审核" },
  employers: { variant: "list", filters: ["单位名称", "联系人", "启用状态"], columns: ["单位名称", "单位类型", "联系人", "联系电话", "可用岗位数", "启用状态"], primaryAction: "新增用人单位", rowAction: "编辑" },
  jobs: { variant: "list", filters: ["岗位名称", "用人单位", "招聘状态"], columns: ["岗位名称", "用人单位", "招聘人数", "薪资标准", "工作时间", "申请人数", "招聘状态"], primaryAction: "发布岗位", rowAction: "管理申请" },
  hardship: { variant: "workflow", filters: ["申请人", "申请种类", "审核状态"], columns: ["申请编号", "申请人", "申请种类", "申请等级", "申请陈述", "当前节点", "审核状态"], primaryAction: "困难补助申请", rowAction: "审核" },
  "hardship-type": { variant: "list", filters: ["补助种类", "启用状态"], columns: ["补助种类", "种类编码", "补助标准", "适用对象", "所需材料", "启用状态"], primaryAction: "新增补助种类", rowAction: "编辑" },
  "hardship-batch": { variant: "workflow", filters: ["批次名称", "学年", "发布状态"], columns: ["批次名称", "学年", "申请开始时间", "申请结束时间", "总名额", "预算金额", "发布状态"], primaryAction: "新增困难补助批次", rowAction: "名额分配" },
  grants: { variant: "workflow", filters: ["申请人", "申请种类", "审核状态"], columns: ["申请编号", "申请人", "申请种类", "申请等级", "申请陈述", "当前节点", "审核状态"], primaryAction: "助学金申请", rowAction: "评定" },
  "grant-type": { variant: "list", filters: ["助学金种类", "启用状态"], columns: ["助学金种类", "种类编码", "等级数量", "金额标准", "评定条件", "启用状态"], primaryAction: "新增助学金种类", rowAction: "编辑" },
  "grant-batch": { variant: "workflow", filters: ["批次名称", "学年", "发布状态"], columns: ["批次名称", "学年", "申请时间", "助学金种类", "总名额", "预算金额", "发布状态"], primaryAction: "新增助学金批次", rowAction: "名额分配" },
  "grant-mutex": { variant: "list", filters: ["互斥组名称", "启用状态"], columns: ["互斥组名称", "包含项目", "互斥规则", "适用学年", "启用状态"], primaryAction: "新增互斥组", rowAction: "配置" },
  "tuition-reduction": { variant: "workflow", filters: ["申请人", "审核状态"], columns: ["申请编号", "申请人", "业务类型", "申请时间", "申请陈述", "当前节点", "审核状态"], primaryAction: "学费减免申请", rowAction: "审核" },
  loans: { variant: "workflow", filters: ["申请人", "审核状态"], columns: ["申请编号", "申请人", "业务类型", "申请时间", "申请陈述", "当前节点", "审核状态"], primaryAction: "贷款登记", rowAction: "办理" },
  scholarship: { variant: "workflow", filters: ["申请人", "申请种类", "审核状态"], columns: ["申请编号", "申请人", "申请种类", "申请等级", "申请陈述", "当前节点", "审核状态"], primaryAction: "奖学金申请", rowAction: "评定" },
  "scholarship-type": { variant: "list", filters: ["奖学金种类", "启用状态"], columns: ["奖学金种类", "种类编码", "等级", "金额标准", "评定条件", "启用状态"], primaryAction: "新增奖学金种类", rowAction: "编辑" },
  "scholarship-batch": { variant: "workflow", filters: ["批次名称", "学年", "发布状态"], columns: ["批次名称", "学年", "申请时间", "奖学金种类", "总名额", "预算金额", "发布状态"], primaryAction: "新增奖学金批次", rowAction: "名额分配" },
  "scholarship-mutex": { variant: "list", filters: ["互斥组名称", "启用状态"], columns: ["互斥组名称", "包含奖项", "互斥规则", "适用学年", "启用状态"], primaryAction: "新增互斥组", rowAction: "配置" },
  "personal-honor": { variant: "workflow", filters: ["申请人", "审核状态"], columns: ["申请编号", "申请人", "业务类型", "申请时间", "申请陈述", "当前节点", "审核状态"], primaryAction: "个人荣誉申报", rowAction: "评定" },
  "collective-honor": { variant: "workflow", filters: ["申请人", "审核状态"], columns: ["申请编号", "申请人", "业务类型", "申请时间", "申请陈述", "当前节点", "审核状态"], primaryAction: "集体荣誉申报", rowAction: "评定" },
  "honor-batch": { variant: "workflow", filters: ["批次名称", "学年", "发布状态"], columns: ["批次名称", "学年", "申报时间", "荣誉类型", "个人名额", "集体名额", "发布状态"], primaryAction: "新增荣誉批次", rowAction: "名额分配" },
  discipline: { variant: "workflow", filters: ["姓名", "学号", "违纪类型", "处理状态"], columns: ["违纪编号", "姓名", "学号", "违纪类型", "违纪时间", "违纪地点", "处理状态"], primaryAction: "违纪登记", rowAction: "处理" },
  "discipline-view": { variant: "list", filters: ["姓名", "学号", "违纪类型", "处理结果"], columns: ["违纪编号", "姓名", "学号", "违纪类型", "违纪事实", "处理结果", "归档时间"], rowAction: "详情" },
  punishment: { variant: "workflow", filters: ["申请人", "审核状态"], columns: ["申请编号", "申请人", "业务类型", "申请时间", "申请陈述", "当前节点", "审核状态"], primaryAction: "处分登记", rowAction: "处理" },
  appeal: { variant: "workflow", filters: ["申请人", "审核状态"], columns: ["申请编号", "申请人", "业务类型", "申请时间", "申请陈述", "当前节点", "审核状态"], primaryAction: "处分申诉", rowAction: "审核" },
  revoke: { variant: "workflow", filters: ["申请人", "审核状态"], columns: ["申请编号", "申请人", "业务类型", "申请时间", "申请陈述", "当前节点", "审核状态"], primaryAction: "处分撤销申请", rowAction: "审核" },
  clubs: { variant: "list", filters: ["社团名称", "社团类别", "运行状态"], columns: ["社团名称", "社团类别", "负责人", "指导教师", "成员人数", "成立日期", "运行状态"], primaryAction: "新增社团", rowAction: "社团详情" },
  "club-apply": { variant: "workflow", filters: ["社团名称", "申请人", "审核状态"], columns: ["社团名称", "社团类别", "申请人", "指导教师", "提交时间", "当前节点", "审核状态"], primaryAction: "成立社团申请", rowAction: "审核" },
  "managed-clubs": { variant: "list", filters: ["社团名称", "运行状态"], columns: ["社团名称", "社团类别", "我的角色", "成员人数", "近期活动", "运行状态"], rowAction: "管理社团" },
  "started-clubs": { variant: "list", filters: ["社团名称", "申请状态"], columns: ["社团名称", "社团类别", "发起时间", "当前节点", "申请状态"], rowAction: "申请详情" },
  "joined-clubs": { variant: "list", filters: ["社团名称", "成员状态"], columns: ["社团名称", "社团类别", "加入时间", "社团职务", "参与活动", "成员状态"], rowAction: "社团详情" },
  "league-member": { variant: "workflow", filters: ["申请人", "审核状态"], columns: ["申请编号", "申请人", "业务类型", "申请时间", "申请陈述", "当前节点", "审核状态"], primaryAction: "入团登记", rowAction: "审核" },
  "second-class": { variant: "workflow", filters: ["申请人", "审核状态"], columns: ["申请编号", "申请人", "业务类型", "申请时间", "申请陈述", "当前节点", "审核状态"], primaryAction: "发布第二课堂活动", rowAction: "管理" },
  transcript: { variant: "list", filters: ["姓名", "学号", "学年"], columns: ["姓名", "学号", "院系", "思想成长", "实践实习", "志愿公益", "文体活动", "总学分"], rowAction: "成绩单" },
  leaving: { variant: "workflow", filters: ["申请人", "审核状态"], columns: ["申请编号", "申请人", "业务类型", "申请时间", "申请陈述", "当前节点", "审核状态"], primaryAction: "发起离校", rowAction: "办理详情" },
  "graduate-direction": { variant: "list", filters: ["姓名", "学号", "毕业去向", "确认状态"], columns: ["姓名", "学号", "院系", "毕业去向", "单位名称", "单位所在地", "填报时间", "确认状态"], primaryAction: "导入毕业去向", rowAction: "确认" },
  "card-checkin": { variant: "list", filters: ["身份证号", "学号", "姓名"], columns: ["姓名", "学号", "院系", "班级", "报到状态", "报到时间"], primaryAction: "刷卡报到", rowAction: "确认报到" },
  "manual-checkin": { variant: "list", filters: ["姓名", "学号", "身份证号", "迎新批次"], columns: ["姓名", "学号", "院系", "缴费状态", "宿舍", "报到环节", "报到状态"], primaryAction: "人工报到", rowAction: "办理" },
  "welcome-payment-list": { variant: "list", filters: ["姓名", "学号", "院系", "缴费状态"], columns: ["姓名", "学号", "应缴金额", "实缴金额", "缴费方式", "缴费时间", "缴费状态"], primaryAction: "导入缴费信息", rowAction: "查看" },
  "welcome-payment-proof": { variant: "list", filters: ["姓名", "学号", "凭证状态"], columns: ["姓名", "学号", "缴费项目", "凭证附件", "提交时间", "审核状态"], rowAction: "审核" },
  "faculty-checkin-stats": { variant: "statistics", filters: ["迎新批次", "学院"], columns: statisticsColumns, metrics: ["应到新生", "已报到", "未报到", "报到率"] },
  "class-checkin-stats": { variant: "statistics", filters: ["迎新批次", "学院", "班级"], columns: ["班级", ...statisticsColumns.slice(1)], metrics: ["覆盖班级", "已报到", "未报到", "报到率"] },
  "live-checkin-stats": { variant: "statistics", filters: ["迎新批次"], columns: ["时间段", "报到人数", "累计人数", "现场窗口"], metrics: ["今日报到", "当前每小时", "开放窗口", "总体进度"] },
  "supplies-stats": { variant: "statistics", filters: ["迎新批次", "用品类型"], columns: ["用品名称", "应发数量", "已发数量", "剩余数量", "领取率"], metrics: ["用品种类", "已领取", "待领取", "领取率"] },
  "transport-stats": { variant: "statistics", filters: ["迎新批次", "到站地点"], columns: ["到站地点", "车次", "预计人数", "已接人数", "车辆状态"], metrics: ["接站点", "班次", "已接人数", "待接人数"] },
  "payment-stats": { variant: "statistics", filters: ["迎新批次", "学院"], columns: ["学院", "应缴人数", "已缴人数", "应缴金额", "实缴金额", "缴费率"], metrics: ["应缴总额", "实缴总额", "未缴人数", "缴费率"] },
  "step-stats": { variant: "statistics", filters: ["迎新批次"], columns: ["迎新环节", "应办理", "已办理", "未办理", "完成率"], metrics: ["流程环节", "已完成", "处理中", "异常环节"] },
  "nation-stats": { variant: "statistics", filters: ["迎新批次", "学院"], columns: ["民族", "人数", "男生", "女生", "占比"], metrics: ["民族数量", "新生总数", "少数民族", "占比"] },
  "welcome-dorm-stats": { variant: "statistics", filters: ["迎新批次", "楼栋"], columns: ["楼栋", "房间数", "总床位", "已分配", "空余床位"], metrics: ["开放楼栋", "总床位", "已分配", "空余床位"] },
  "welcome-process": { variant: "workflow", filters: ["迎新批次"], columns: ["环节名称", "办理顺序", "责任部门", "是否必办", "启用状态"], primaryAction: "添加环节", rowAction: "配置" },
  "dorm-building": { variant: "list", filters: ["校区", "楼栋名称", "住宿性别", "启用状态"], columns: ["校区", "楼栋名称", "楼层数", "房间数", "住宿性别", "楼栋管理员", "启用状态"], primaryAction: "新增楼栋", rowAction: "编辑" },
  "dorm-room": { variant: "list", filters: ["校区", "楼栋", "房间号", "房间状态"], columns: ["楼栋", "房间号", "楼层", "房间类型", "床位数", "已住人数", "空床数", "房间状态"], primaryAction: "新增宿舍", rowAction: "床位管理" },
  "dorm-occupancy": { variant: "list", filters: ["楼栋", "房间号", "姓名", "学号"], columns: ["楼栋", "房间号", "床位号", "姓名", "学号", "院系", "入住日期", "住宿状态"], rowAction: "住宿详情" },
  "dorm-batch": { variant: "workflow", filters: ["批次名称", "学年", "状态"], columns: ["批次名称", "适用学生", "可分配楼栋", "排宿方式", "开始时间", "结束时间", "状态"], primaryAction: "新建排宿批次", rowAction: "进入排宿" },
  "dorm-assign": { variant: "workflow", filters: ["排宿批次", "学院", "性别"], columns: ["学生范围", "待排人数", "可用床位", "已分配", "未分配", "冲突数", "分配状态"], primaryAction: "自动分配", rowAction: "查看结果" },
  "dorm-movement-list": { variant: "list", filters: ["申办类型", "姓名", "学号", "审核状态"], columns: ["申请编号", "姓名", "学号", "申办类型", "原宿舍", "目标宿舍", "申请时间", "审核状态"], rowAction: "审核" },
  "dorm-movement-log": { variant: "logs", filters: ["姓名", "学号", "变动类型", "时间范围"], columns: ["姓名", "学号", "变动类型", "原住宿", "新住宿", "操作人", "操作时间"], rowAction: "详情" },
  "room-hygiene": { variant: "list", filters: ["检查日期", "楼栋", "房间号"], columns: ["检查日期", "楼栋", "房间号", "卫生得分", "扣分项", "检查人", "整改状态"], primaryAction: "检查登记", rowAction: "整改详情" },
  "student-hygiene": { variant: "list", filters: ["检查日期", "姓名", "学号", "楼栋"], columns: ["姓名", "学号", "宿舍", "个人得分", "扣分项", "检查日期", "整改状态"], primaryAction: "个人检查登记", rowAction: "详情" },
  "dorm-discipline": { variant: "list", filters: ["姓名", "学号", "违纪类型", "处理状态"], columns: ["姓名", "学号", "宿舍", "违纪类型", "违纪时间", "扣分", "处理状态"], primaryAction: "违纪登记", rowAction: "处理" },
  "dorm-attendance": { variant: "list", filters: ["考勤日期", "楼栋", "姓名", "考勤状态"], columns: ["日期", "姓名", "学号", "宿舍", "签到时间", "定位结果", "考勤状态"], primaryAction: "导入考勤", rowAction: "核实" },
  "dorm-attendance-stats": { variant: "statistics", filters: ["时间范围", "楼栋", "学院"], columns: ["统计维度", "应到", "正常", "晚归", "未归", "异常率"], metrics: ["应到人数", "正常", "晚归", "未归"] },
  "dorm-repair": { variant: "list", filters: ["报修编号", "楼栋", "报修类型", "维修状态"], columns: ["报修编号", "报修位置", "报修类型", "故障描述", "报修人", "维修人员", "提交时间", "维修状态"], primaryAction: "新增报修", rowAction: "派单" },
  "role-admin": { variant: "list", filters: ["角色名称", "角色别名", "启用状态"], columns: ["角色名称", "角色别名", "排序", "用户数", "数据范围", "启用状态"], primaryAction: "新增角色", rowAction: "权限配置" },
  "data-permission": { variant: "list", filters: ["角色名称", "数据范围"], columns: ["角色名称", "所属租户", "数据范围", "已授权机构", "更新时间", "状态"], primaryAction: "新增授权", rowAction: "配置范围" },
  "api-permission": { variant: "list", filters: ["角色名称", "接口名称", "请求方式"], columns: ["接口名称", "接口路径", "请求方式", "所属服务", "授权角色", "状态"], primaryAction: "接口授权", rowAction: "配置" },
  "user-admin": { variant: "list", filters: ["账号", "姓名", "机构", "角色", "状态"], columns: ["账号", "姓名", "机构", "岗位", "角色", "手机号", "登录次数", "状态"], primaryAction: "新增用户", rowAction: "编辑" },
  "menu-admin": { variant: "list", filters: ["菜单名称", "菜单类型", "所属系统"], columns: ["菜单名称", "路由地址", "组件路径", "菜单类型", "权限标识", "排序", "状态"], primaryAction: "新增菜单", rowAction: "配置" },
  "usual-log": { variant: "logs", filters: ["服务名称", "操作人", "日志级别", "时间范围"], columns: ["服务名称", "操作模块", "操作类型", "操作人", "客户端IP", "操作时间", "执行结果"], rowAction: "详情" },
  "api-log": { variant: "logs", filters: ["服务名称", "接口路径", "请求方式", "状态码"], columns: ["追踪ID", "服务名称", "接口路径", "请求方式", "状态码", "耗时", "请求时间"], rowAction: "详情" },
  "error-log": { variant: "logs", filters: ["服务名称", "异常类型", "时间范围"], columns: ["追踪ID", "服务名称", "请求地址", "异常类型", "异常信息", "操作人", "发生时间"], rowAction: "异常详情" },
  "honor-type": { variant: "list", filters: ["称号名称", "荣誉级别", "启用状态"], columns: ["称号名称", "称号编码", "荣誉级别", "适用对象", "评定条件", "启用状态"], primaryAction: "新增荣誉称号", rowAction: "编辑" },
  "discipline-type": { variant: "list", filters: ["违纪类型", "适用范围", "启用状态"], columns: ["违纪类型", "类型编码", "违纪等级", "默认扣分", "适用范围", "启用状态"], primaryAction: "新增违纪类型", rowAction: "编辑" },
  "punishment-type": { variant: "list", filters: ["处分类型", "处分等级", "启用状态"], columns: ["处分类型", "类型编码", "处分等级", "影响期限", "撤销条件", "启用状态"], primaryAction: "新增处分类型", rowAction: "编辑" },
  "second-class-rules": { variant: "list", filters: ["规则名称", "所属模块", "启用状态"], columns: ["规则名称", "所属模块", "活动级别", "积分标准", "年度上限", "启用状态"], primaryAction: "新增积分规则", rowAction: "配置" },
  "welcome-notes": { variant: "list", filters: ["须知标题", "迎新批次", "发布状态"], columns: ["须知标题", "迎新批次", "发布范围", "发布时间", "阅读人数", "发布状态"], primaryAction: "新增报到须知", rowAction: "编辑" },
  "welcome-faq": { variant: "list", filters: ["问题关键字", "问题分类", "启用状态"], columns: ["问题标题", "问题分类", "答案摘要", "显示排序", "更新时间", "启用状态"], primaryAction: "新增常见问题", rowAction: "编辑" },
  "welcome-batch": { variant: "workflow", filters: ["批次名称", "入学年份", "发布状态"], columns: ["批次名称", "入学年份", "报到开始时间", "报到结束时间", "新生人数", "流程数量", "发布状态"], primaryAction: "新增迎新批次", rowAction: "批次配置" },
  "dorm-checkin": { variant: "workflow", filters: ["申请人", "申办类型", "审核状态"], columns: ["申请编号", "申请人", "申办类型", "申办说明", "当前节点", "审核状态"], primaryAction: "入住申请", rowAction: "审核" },
  "dorm-transfer": { variant: "workflow", filters: ["申请人", "审核状态"], columns: ["申请编号", "申请人", "申请类型", "申请陈述", "当前节点", "审核状态"], primaryAction: "调整宿舍申请", rowAction: "审核" },
  "dorm-checkout": { variant: "workflow", filters: ["申请人", "审核状态"], columns: ["申请编号", "申请人", "申请类型", "申请陈述", "当前节点", "审核状态"], primaryAction: "退宿申请", rowAction: "审核" },
  "holiday-dorm": { variant: "workflow", filters: ["申请人", "审核状态"], columns: ["申请编号", "申请人", "申请类型", "申请陈述", "当前节点", "审核状态"], primaryAction: "假期留宿申请", rowAction: "审核" },
  "delayed-checkout": { variant: "workflow", filters: ["申请人", "审核状态"], columns: ["申请编号", "申请人", "申请类型", "申请陈述", "当前节点", "审核状态"], primaryAction: "延缓退宿申请", rowAction: "审核" },
  "hygiene-deduction": { variant: "list", filters: ["扣分项名称", "适用对象", "启用状态"], columns: ["扣分项名称", "扣分编码", "扣分值", "适用对象", "整改期限", "启用状态"], primaryAction: "新增卫生扣分项", rowAction: "编辑" },
  "dorm-discipline-type": { variant: "list", filters: ["违纪类型", "违纪等级", "启用状态"], columns: ["违纪类型", "类型编码", "违纪等级", "默认扣分", "处理方式", "启用状态"], primaryAction: "新增宿舍违纪类型", rowAction: "编辑" },
  "attendance-exception-type": { variant: "list", filters: ["异常类型", "处理级别", "启用状态"], columns: ["异常类型", "类型编码", "判定规则", "处理级别", "通知对象", "启用状态"], primaryAction: "新增异常类型", rowAction: "编辑" },
  "location-rule": { variant: "list", filters: ["规则名称", "适用楼栋", "启用状态"], columns: ["规则名称", "适用楼栋", "定位方式", "有效半径", "签到时段", "启用状态"], primaryAction: "新增定位规则", rowAction: "配置" },
  "model-design": { variant: "list", filters: ["模型名称", "模型标识", "模型状态"], columns: ["模型名称", "模型标识", "版本号", "流程分类", "部署状态", "更新时间"], primaryAction: "新建模型", rowAction: "设计" },
  "form-design": { variant: "list", filters: ["表单名称", "表单分类", "启用状态"], columns: ["表单名称", "表单编码", "关联模型", "字段数量", "更新时间", "启用状态"], primaryAction: "新建表单", rowAction: "设计" },
  "deployment": { variant: "list", filters: ["流程名称", "流程分类", "部署状态"], columns: ["流程名称", "流程标识", "版本号", "部署时间", "部署人", "部署状态"], primaryAction: "部署流程", rowAction: "版本管理" },
  "flow-button": { variant: "list", filters: ["按钮名称", "按钮类型", "启用状态"], columns: ["按钮名称", "按钮编码", "按钮类型", "触发动作", "显示排序", "启用状态"], primaryAction: "新增流程按钮", rowAction: "编辑" },
  "flow-category": { variant: "list", filters: ["分类名称", "分类编码", "启用状态"], columns: ["分类名称", "分类编码", "上级分类", "流程数量", "显示排序", "启用状态"], primaryAction: "新增流程分类", rowAction: "编辑" },
  "form-default": { variant: "list", filters: ["表单名称", "字段名称", "启用状态"], columns: ["表单名称", "字段名称", "默认值类型", "默认值表达式", "适用流程", "启用状态"], primaryAction: "新增默认值", rowAction: "编辑" },
  "flow-expression": { variant: "list", filters: ["表达式名称", "表达式类型", "启用状态"], columns: ["表达式名称", "表达式编码", "表达式类型", "表达式内容", "引用次数", "启用状态"], primaryAction: "新增流程表达式", rowAction: "编辑" },
  "new-flow": { variant: "workflow", filters: ["流程名称", "流程分类", "发布状态"], columns: ["流程名称", "流程分类", "发起范围", "审批层级", "更新时间", "发布状态"], primaryAction: "发起新流程", rowAction: "发起" },
  "todo": { variant: "workflow", filters: ["流程名称", "发起人", "到达时间"], columns: ["任务编号", "流程名称", "发起人", "当前节点", "到达时间", "剩余时限", "任务状态"], rowAction: "办理" },
  "my-request": { variant: "workflow", filters: ["流程名称", "发起时间", "流程状态"], columns: ["请求编号", "流程名称", "当前节点", "发起时间", "最近处理人", "流程状态"], rowAction: "流程详情" },
  "my-done": { variant: "logs", filters: ["流程名称", "办理时间", "处理结果"], columns: ["任务编号", "流程名称", "发起人", "办理节点", "办理时间", "处理结果"], rowAction: "办理详情" },
  "finished": { variant: "logs", filters: ["流程名称", "发起人", "办结时间"], columns: ["流程实例号", "流程名称", "发起人", "发起时间", "办结时间", "最终结果"], rowAction: "流程详情" },
  "claim": { variant: "workflow", filters: ["流程名称", "任务节点", "到达时间"], columns: ["任务编号", "流程名称", "发起人", "任务节点", "候选角色", "到达时间", "任务状态"], rowAction: "签收" },
  "copied": { variant: "logs", filters: ["流程名称", "抄送人", "阅读状态"], columns: ["抄送编号", "流程名称", "发起人", "抄送人", "抄送时间", "阅读状态"], rowAction: "查看" },
  "ops-schedule": { variant: "workflow", filters: ["流程名称", "发起人", "运行状态"], columns: ["实例编号", "流程名称", "当前节点", "当前处理人", "停留时长", "运行状态"], primaryAction: "运维调度", rowAction: "调度" },
  "ops-finished": { variant: "logs", filters: ["流程名称", "办结时间", "结束类型"], columns: ["实例编号", "流程名称", "发起人", "发起时间", "办结时间", "结束类型"], rowAction: "详情" },
  "process-list": { variant: "logs", filters: ["流程名称", "流程分类", "运行状态"], columns: ["实例编号", "流程名称", "业务主键", "发起人", "当前节点", "发起时间", "运行状态"], rowAction: "实例详情" },
  "process-agent": { variant: "list", filters: ["委托人", "代理人", "启用状态"], columns: ["委托人", "代理人", "代理流程", "开始时间", "结束时间", "启用状态"], primaryAction: "新增流程代理", rowAction: "编辑" },
  "team-building": { variant: "list", filters: ["姓名", "队伍类型", "任职状态"], columns: ["姓名", "工号", "队伍类型", "所属院系", "任职职务", "任职时间", "任职状态"], primaryAction: "新增队伍成员", rowAction: "维护" },
  "headteacher-query": { variant: "list", filters: ["姓名", "工号", "院系", "任职学年"], columns: ["姓名", "工号", "院系", "所带班级", "任职学年", "聘任时间", "任职状态"], rowAction: "任职详情" },
  "home-carousel": { variant: "list", filters: ["轮播标题", "展示位置", "发布状态"], columns: ["轮播标题", "封面图片", "跳转地址", "展示位置", "排序", "有效时间", "发布状态"], primaryAction: "新增首页轮播", rowAction: "编辑" },
  "announcement": { variant: "list", filters: ["公告标题", "公告类型", "发布状态"], columns: ["公告标题", "公告类型", "发布范围", "发布人", "发布时间", "阅读人数", "发布状态"], primaryAction: "发布通知公告", rowAction: "编辑" },
  "campus-news": { variant: "list", filters: ["新闻标题", "新闻分类", "发布状态"], columns: ["新闻标题", "新闻分类", "封面图片", "发布部门", "发布时间", "浏览量", "发布状态"], primaryAction: "发布校内新闻", rowAction: "编辑" },
  "faculty-admin": { variant: "list", filters: ["学院名称", "学院代码", "启用状态"], columns: ["学院名称", "学院代码", "学院简称", "负责人", "联系电话", "专业数量", "启用状态"], primaryAction: "新增学院", rowAction: "编辑" },
  "major-admin": { variant: "list", filters: ["专业名称", "专业代码", "所属学院"], columns: ["专业名称", "专业代码", "所属学院", "培养层次", "学制", "负责人", "启用状态"], primaryAction: "新增专业", rowAction: "编辑" },
  "class-admin": { variant: "list", filters: ["班级名称", "班级代码", "所属专业", "入学年级"], columns: ["班级名称", "班级代码", "所属专业", "所属学院", "入学年级", "班主任", "学生人数", "启用状态"], primaryAction: "新增班级", rowAction: "编辑" },
  "org-admin": { variant: "list", filters: ["机构名称", "机构类型", "启用状态"], columns: ["机构名称", "机构编码", "上级机构", "机构类型", "负责人", "显示排序", "启用状态"], primaryAction: "新增机构", rowAction: "编辑" },
  "post-admin": { variant: "list", filters: ["岗位名称", "岗位编码", "启用状态"], columns: ["岗位名称", "岗位编码", "所属机构", "岗位类别", "用户数量", "显示排序", "启用状态"], primaryAction: "新增岗位", rowAction: "编辑" },
  "system-dict": { variant: "list", filters: ["字典名称", "字典编码", "启用状态"], columns: ["字典名称", "字典编码", "字典类型", "字典项数量", "更新时间", "启用状态"], primaryAction: "新增系统字典", rowAction: "字典项" },
  "business-dict": { variant: "list", filters: ["字典名称", "所属业务", "启用状态"], columns: ["字典名称", "字典编码", "所属业务", "字典项数量", "更新时间", "启用状态"], primaryAction: "新增业务字典", rowAction: "字典项" },
  "top-menu": { variant: "list", filters: ["菜单名称", "所属系统", "启用状态"], columns: ["菜单名称", "所属系统", "图标", "跳转地址", "显示排序", "启用状态"], primaryAction: "新增顶部菜单", rowAction: "编辑" },
  "morning-exercise": { variant: "list", filters: ["考勤日期", "区队", "姓名", "考勤状态"], columns: ["日期", "姓名", "学号", "区队", "集合时间", "缺勤原因", "考勤状态"], primaryAction: "导入考勤", rowAction: "核实" },
  "appearance-inspection": { variant: "list", filters: ["检查日期", "区队", "姓名", "检查结果"], columns: ["检查日期", "姓名", "学号", "区队", "检查项目", "扣分", "检查结果", "检查人"], primaryAction: "检查登记", rowAction: "详情" },
  "conduct-score": { variant: "list", filters: ["区队", "姓名", "加减分", "记录日期"], columns: ["记录日期", "姓名", "学号", "区队", "加减分", "事由", "分值", "记录人"], primaryAction: "操行分登记", rowAction: "编辑" },
  "conduct-score-stats": { variant: "statistics", filters: ["时间范围", "区队"], columns: ["统计维度", "基础分", "加分", "扣分", "当前得分"], metrics: ["覆盖区队", "平均得分", "累计加分", "累计扣分"] },
  "physical-test": { variant: "list", filters: ["学号", "姓名", "测试项目", "成绩评定"], columns: ["测试日期", "姓名", "学号", "区队", "测试项目", "成绩", "成绩评定"], primaryAction: "导入体测数据", rowAction: "编辑" },
  "police-training": { variant: "list", filters: ["训练日期", "训练科目", "区队", "考勤状态"], columns: ["训练日期", "训练科目", "姓名", "学号", "区队", "考勤状态", "备注"], primaryAction: "导入考勤", rowAction: "核实" },
  "duty-assignment": { variant: "list", filters: ["执勤日期", "执勤地点", "区队", "姓名"], columns: ["执勤日期", "执勤时段", "执勤地点", "姓名", "学号", "区队", "带队教师", "执勤状态"], primaryAction: "安排执勤", rowAction: "编辑" },
  "emergency-drill": { variant: "list", filters: ["演练名称", "演练类型", "开展日期"], columns: ["演练名称", "演练类型", "开展日期", "参与区队", "参与人数", "完成用时(分)", "演练评价", "组织者"], primaryAction: "演练登记", rowAction: "详情" },
  "political-review": { variant: "list", filters: ["姓名", "学号", "审查状态"], columns: ["姓名", "学号", "区队", "审查类别", "提交日期", "审查意见", "审查状态"], primaryAction: "新增档案", rowAction: "详情" },
};

export function getPresentation(featureId: string, stage?: string): FeaturePresentation {
  return featurePresentations[featureId] ?? {
    variant: stage === "archive" ? "list" : "list",
    filters: ["关键字", "状态", "时间范围"],
    columns: ["业务编号", "名称", "所属范围", "创建时间", "当前状态"],
    primaryAction: stage === "archive" ? undefined : "新建记录",
    rowAction: stage === "review" ? "审核" : "查看",
  };
}

// Real business options for status-like filters; falls back to keyword matching.
const exactFilterOptions: Record<string, string[]> = {
  审核状态: ["待审核", "审核中", "已通过", "已驳回"],
  处理状态: ["待处理", "处理中", "已办结"],
  处理结果: ["同意", "驳回", "转办"],
  申请状态: ["待审核", "审核中", "已录用", "未录用"],
  发布状态: ["未发布", "申请中", "已发布", "已结束"],
  运行状态: ["运行中", "已暂停", "已终止"],
  流程状态: ["运行中", "已完成", "已终止"],
  模型状态: ["草稿", "已发布", "已停用"],
  启用状态: ["启用", "停用"],
  缴费状态: ["未缴费", "部分缴费", "已缴清"],
  凭证状态: ["待审核", "已通过", "已驳回"],
  请假类型: ["事假", "病假", "公假", "其他"],
  销假状态: ["待审核", "已销假", "已驳回"],
  返校状态: ["待确认", "已返校", "未返校"],
  确认状态: ["待确认", "已确认"],
  办理状态: ["待办理", "办理中", "已完成"],
  处分状态: ["生效中", "已解除", "已撤销"],
  申诉状态: ["待受理", "处理中", "已办结"],
  贷款状态: ["待审核", "已通过", "已放款", "已驳回"],
  入团状态: ["群众", "入团积极分子", "共青团员"],
  入党状态: ["群众", "入党积极分子", "预备党员", "中共党员"],
  招聘状态: ["招聘中", "已截止", "已结束"],
  申办类型: ["补办", "换发"],
  阅读状态: ["未读", "已读"],
  成员状态: ["在任", "已离任"],
  任职状态: ["在任", "已离任"],
  撤销状态: ["未撤销", "已撤销"],
  维修状态: ["待派单", "维修中", "已完成"],
  考勤状态: ["正常", "迟到", "早退", "缺勤", "晚归"],
  房间状态: ["正常", "空置", "维修中"],
  住宿状态: ["在住", "调宿", "退宿"],
  报到状态: ["待报到", "已报到"],
  整改状态: ["待整改", "整改中", "已完成"],
  违纪类型: ["晚归", "违规电器", "卫生不合格", "夜不归宿"],
  违纪等级: ["警告", "严重警告", "记过", "留校察看"],
  处分类型: ["警告", "严重警告", "记过", "留校察看", "开除学籍"],
  处分等级: ["警告", "严重警告", "记过", "留校察看", "开除学籍"],
  投诉类型: ["后勤服务", "教学管理", "学生事务", "校园安全", "其他"],
  报修类型: ["水电维修", "家具维修", "网络故障", "门窗维修", "其他"],
  荣誉级别: ["国家级", "省级", "市级", "校级", "院级"],
  困难等级: ["特别困难", "困难", "一般困难"],
  毕业去向: ["就业", "升学", "参军", "创业", "回生源地"],
  机构类型: ["学院", "部门", "班级", "社团"],
  性别: ["男", "女"],
  请求方式: ["GET", "POST", "PUT", "DELETE"],
  数据范围: ["本机构及下级", "本机构", "仅本人"],
  日志级别: ["INFO", "WARN", "ERROR", "DEBUG"],
  所属系统: ["学生端", "迎新系统", "宿舍系统", "管理端"],
  结束类型: ["正常办结", "撤回终止", "超时终止"],
  变动类型: ["调入", "调出", "专业变更", "年级变更"],
  退宿类型: ["毕业退宿", "休学退宿", "调宿退宿", "其他"],
};

export function filterOptionsFor(filter: string): string[] | null {
  if (exactFilterOptions[filter]) return exactFilterOptions[filter];
  if (filter.endsWith("状态") || filter === "状态") return ["待处理", "处理中", "已完成"];
  if (filter.includes("方式") && filter !== "请求方式") return null;
  return null;
}
