"use client";

import { FormSection } from "./FormSection";
import type { FieldSpec } from "./FormField";

export function ConfigRecordForm({ featureId, feature }: { featureId: string; feature: string }) {
  const schemas: Record<string, FieldSpec[]> = {
    "dorm-building": [{ label: "所属校区", required: true, type: "select", options: ["滨湖校区", "城南校区"] }, { label: "楼栋名称", required: true }, { label: "楼栋代码", required: true }, { label: "楼层数", required: true, type: "number" }, { label: "住宿性别", required: true, type: "select", options: ["男", "女", "混合"] }, { label: "楼栋管理员", type: "select", options: ["王老师", "李老师"] }, { label: "联系电话" }, { label: "楼栋地址" }, { label: "启用状态", type: "select", options: ["启用", "停用"] }],
    "dorm-room": [{ label: "所属楼栋", required: true, type: "select", options: ["海棠1号楼", "海棠2号楼"] }, { label: "房间号", required: true }, { label: "所在楼层", required: true, type: "number" }, { label: "房间类型", required: true, type: "select", options: ["四人间", "六人间", "八人间"] }, { label: "床位数量", required: true, type: "number" }, { label: "住宿费用", type: "number" }, { label: "房间状态", type: "select", options: ["正常", "维修", "停用"] }, { label: "房间设施", type: "textarea" }],
    "welcome-process": [{ label: "环节名称", required: true }, { label: "环节代码", required: true }, { label: "办理顺序", required: true, type: "number" }, { label: "责任部门", required: true, type: "select", options: ["招生办", "财务处", "学生处", "后勤处"] }, { label: "是否必办", type: "select" }, { label: "办理地址" }, { label: "办理说明", type: "textarea" }],
    "role-admin": [{ label: "角色名称", required: true }, { label: "角色别名", required: true }, { label: "角色排序", type: "number" }, { label: "所属租户", type: "select", options: ["智慧学工", "学校本部"] }, { label: "数据范围", type: "select", options: ["全部数据", "本机构及下级", "本机构", "仅本人"] }, { label: "启用状态", type: "select", options: ["启用", "停用"] }, { label: "角色备注", type: "textarea" }],
    "data-permission": [{ label: "授权角色", required: true, type: "select", options: ["院系管理员", "辅导员", "宿管员"] }, { label: "数据范围", required: true, type: "select", options: ["全部数据", "本机构及下级", "本机构", "自定义机构", "仅本人"] }, { label: "授权机构", type: "select", options: ["全部机构", "信息工程学院", "商学院"] }, { label: "是否包含下级", type: "select" }, { label: "生效日期", type: "date" }, { label: "失效日期", type: "date" }],
    "api-permission": [{ label: "授权角色", required: true, type: "select", options: ["院系管理员", "辅导员"] }, { label: "所属服务", required: true, type: "select", options: ["blade-student", "blade-dorm", "blade-system"] }, { label: "接口路径", required: true }, { label: "请求方式", required: true, type: "select", options: ["GET", "POST", "PUT", "DELETE"] }, { label: "接口权限标识" }, { label: "启用状态", type: "select", options: ["启用", "停用"] }],
    "user-admin": [{ label: "登录账号", required: true }, { label: "用户姓名", required: true }, { label: "所属机构", required: true, type: "select", options: ["信息工程学院", "商学院", "学生工作处"] }, { label: "所属岗位", type: "select", options: ["辅导员", "管理员", "宿管员"] }, { label: "用户角色", required: true, type: "select", options: ["院系管理员", "辅导员", "宿管员"] }, { label: "手机号码" }, { label: "电子邮箱" }, { label: "账号状态", type: "select", options: ["启用", "锁定", "停用"] }],
    "menu-admin": [{ label: "上级菜单", type: "select", options: ["顶级菜单", "系统管理", "权限管理"] }, { label: "菜单名称", required: true }, { label: "菜单类型", required: true, type: "select", options: ["目录", "菜单", "按钮"] }, { label: "路由地址", required: true }, { label: "组件路径" }, { label: "权限标识" }, { label: "显示排序", type: "number" }, { label: "菜单图标" }, { label: "是否缓存", type: "select" }, { label: "显示状态", type: "select", options: ["显示", "隐藏"] }],
  };
  const fields = schemas[featureId] ?? [{ label: "名称", required: true }, { label: "业务编码", required: true }, { label: "排序号", type: "number", value: "1" }, { label: "启用状态", required: true, type: "select", options: ["启用", "停用"] }, { label: "适用范围", type: "select", options: ["全校", "指定院系", "指定年级"] }, { label: "说明", type: "textarea" }];
  return <><FormSection title={`${feature}配置`} fields={fields} /><FormSection title="规则设置" fields={[{ label: "生效日期", type: "date" }, { label: "失效日期", type: "date" }, { label: "是否允许修改", type: "select" }]} /></>;
}
